/**
 * GitHub PR creation via Octokit.
 *
 * The client is created through a factory so tests can inject a stub — no test
 * in this repo talks to github.com.
 */
import { UpstreamError } from "../../lib/errors.js";
import { redactString } from "../../lib/redact.js";

/** Title from the task, truncated at a word boundary where possible. */
export function prTitleFromTask(task, { max = 72 } = {}) {
  const firstLine = String(task).split("\n")[0].trim();
  if (firstLine.length <= max) return firstLine;
  const cut = firstLine.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

/**
 * A PR body a reviewer can actually act on: what was asked, what was planned,
 * what changed, and — crucially — the evidence that it was verified.
 */
export function buildPrBody(job) {
  const fileRows = (job.files ?? []).map((f) => `| \`${f.path}\` | ${f.action} |`).join("\n");

  const verdict = (result) => {
    if (!result) return "not run";
    if (result.skipped) return "skipped (no command configured)";
    return result.ok ? `passed (\`${result.command}\`)` : `FAILED (\`${result.command}\`)`;
  };

  return [
    `## Task`,
    job.task,
    ``,
    `## Plan`,
    job.plan?.summary ?? "_no plan recorded_",
    job.plan?.notes ? `\n${job.plan.notes}` : "",
    ``,
    `## Files changed`,
    `| File | Action |`,
    `| --- | --- |`,
    fileRows || "| _none_ | |",
    ``,
    `## Verification`,
    `- Lint: ${verdict(job.verification?.lint)}`,
    `- Tests: ${verdict(job.verification?.tests)}`,
    job.verification?.repairAttempts
      ? `- Repair rounds used: ${job.verification.repairAttempts}`
      : "",
    ``,
    `---`,
    `Generated by LLM Council Code+PR mode using \`${job.model}\`. Reviewed and approved before push.`,
  ]
    .filter((line) => line !== "")
    .join("\n");
}

/**
 * @param {object} deps
 * @param {object} deps.config
 * @param {object} [deps.octokit] Injected in tests.
 */
export function createGithubClient({ config, octokit }) {
  async function client() {
    if (octokit) return octokit;
    if (!config.GITHUB_TOKEN) {
      throw new UpstreamError("GITHUB_TOKEN is not configured; cannot open a pull request");
    }
    const { Octokit } = await import("@octokit/rest");
    return new Octokit({ auth: config.GITHUB_TOKEN });
  }

  return {
    async createPullRequest({ title, body, head, base }) {
      if (!config.GITHUB_OWNER || !config.GITHUB_REPO) {
        throw new UpstreamError(
          "GITHUB_OWNER and GITHUB_REPO must be configured to open a pull request",
        );
      }

      try {
        const gh = await client();
        const { data } = await gh.pulls.create({
          owner: config.GITHUB_OWNER,
          repo: config.GITHUB_REPO,
          title,
          body,
          head,
          base,
        });
        return { url: data.html_url, number: data.number };
      } catch (err) {
        // A GitHub error can echo the request, and the request carried a token.
        throw new UpstreamError(
          `Failed to open pull request: ${redactString(err.message ?? "unknown error")}`,
          { cause: err },
        );
      }
    },
  };
}
